import Banner from '../components/common/Banner';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faHandPointRight } from '@fortawesome/free-solid-svg-icons';

const TermsOfUse = () => {
    return (
        <div className="bg-white">
            <Banner
                title="Privacy Policy"
                breadcrumbs={[
                    { label: 'Home', path: '/' },
                    { label: 'Terms of Use', path: '/terms-of-use' }
                ]}
                backgroundImage="/images/terms-banner.jpg"
            />

            {/* Content Section */}
            <section className="container mx-auto px-4 py-16">
                <div className="">
                    <h2 className="text-[26px] lg:text-[32px] xl:text-[36px] text-[#0A1A3A] mb-8">
                        Terms of <span className="text-[#E6AF1C] font-semibold">Use</span>
                    </h2>

                    {/* Terms of use */}
                    <div className="mb-8">
                        <h3 className="text-[18px] font-semibold text-[#E6AF1C] mb-4">Terms of use</h3>
                        <p className="text-[#575455] text-[16px] leading-relaxed mb-4">
                            This Terms of User Agreement (“User Agreement”) lays out the terms and conditions for governing the user’s access and use of services on the Website/ Mobile Application including any other sub-domain or platform which is owned, developed, managed or operated by Finyzer Assets Fintech Services Private Limited ("Finyzer Assets"), and/or its affiliates (hereinafter referred to as "Website"). By using or accessing the Website, using the services, the User accepts and agrees to be bound by the Terms of Use. If the User does not agree with the Terms of Use then the User may immediately exit the Website.
                        </p>
                        <p className="text-[#575455] text-[16px] leading-relaxed mb-4">
                            In terms of the Information Technology Act, 2000, this document is an electronic record, being generated by a computer system, and it does not require any physical or digital signature. Your acceptance of the terms and conditions shall be considered as your consent to use the App, the Website, the services and products (collectively referred to herein as "Services") provided by Finyzer Assets in accordance with the terms and conditions laid down by Finyzer Assets.
                        </p>
                        <p className="text-[#575455] text-[16px] leading-relaxed">
                            This User Agreement is published in accordance with the Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that requires intermediaries to publish the rules and regulations, privacy policy and user agreement for access or usage of the intermediary's computer resource by Users.
                        </p>
                    </div>



                    {/* About Finyzer Assets */}
                    <div className="mb-8">
                        <h3 className="text-[18px] font-semibold text-[#E6AF1C] mb-4">About Finyzer Assets</h3>
                        <p className="text-[#575455] text-[16px] leading-relaxed">
                            Finyzer Assets is engaged in the business of financial product distribution and allied services. Finyzer Assets and its Finyzer Assets Sub Brokers are mutual fund distributors registered with AMFI. In accordance with the applicable laws, Finyzer Assets and Finyzer Assets Sub Brokers are permitted to only render incidental advice with respect to mutual fund products only to its mutual fund distribution client. For every other purpose, including distribution of non-mutual fund products, all material displayed on the Website is for informational purposes only. Further, it is not intended as investment advice or an opinion concerning securities or a public offer proving a basis for an investment decision. No material /information contained on the Website constitutes or shall be interpreted as investment advice, offer, solicitation or advertising with respect to the purchase or sale of any security and no part of it shall form the basis of or be relied upon in connection with any contract or commitment whatsoever. Finyzer Assets and/or Finyzer Assets Sub Brokers, in association with Finyzer Assets, may also be engaged in 'distribution only' of other financial and investment products, including but not limited to portfolio management products, bank and corporate fixed deposits, bonds, gold bonds, convertible debentures, debentures, national pension scheme and loan products, etc, as available/ offered on primary and secondary security markets and/or in direct arrangement with such third parties issuing/providing such products. Each of such activities is done independently. Finyzer Assets and Finyzer Assets Sub Brokers do not provide any advice with respect to such products and the activity is strictly restricted to distribution only under extant applicable laws. Finyzer Assets and Finyzer Assets Sub Brokers do not provide any investment advisory services w.r.t. such non-mutual fund products and any information provided thereof should not be relied upon while making an investment in such investment products.
                        </p>
                    </div>

                    {/* Interpretation */}
                    <div className="mb-8">
                        <h3 className="text-[18px] font-semibold text-[#E6AF1C] mb-4">Interpretation</h3>
                        <p className="text-[#575455] text-[16px] leading-relaxed mb-4">
                            The words, "him", "his", "You", "Your", "Client", "User" "Investor", "Subscriber" and "Customer" refer to the person(s) who use and avail the Services and Products of Finyzer Assets Website / App and shall include both singular and plural. All headings, bold typing and italics (if any) have been inserted for convenience of reference only and do not define, limit or affect the meaning or interpretation of the terms contained herein.
                        </p>
                        <p className="text-[#575455] text-[16px] leading-relaxed mb-4">
                            These terms shall constitute a binding contract between Finyzer Assets and you when you download the App or use the services on the Website and/or the App or use its Services on any other platform managed by Finyzer Assets and shall be referred to herein as the "Agreement". Downloading and installing the App or using the services of the Website or the App shall be deemed to constitute sufficient proof that you have read, understood and accepted these terms.
                        </p>
                        <p className="text-[#575455] text-[16px] leading-relaxed mb-4">
                            By accessing the Website, downloading the app or the usage of the services the User acknowledges to have read, understood and agrees to be legally bound by this User Agreement. Finyzer Assets reserves the right to change the terms and conditions at any time, without any notice. User’s continued use of the Website after the changes to the Terms are made shall be considered as acceptance from User for the changes.
                        </p>
                        <p className="text-[#575455] text-[16px] leading-relaxed mb-4">
                            This User Agreement contains important information regarding the Services that Finyzer Assets will provide to you, and for your own protection, the Users must read them carefully before accepting the same. If you do not agree to these terms contained herein, you must not proceed to use the Website, App or use the Services provided on the Website or App.
                        </p>
                        <p className="text-[#575455] text-[16px] leading-relaxed mb-4">
                            This User Agreement must be read in consonance with the privacy policy document or other such documents as may be applicable to a particular account/service/situation/circumstance/transaction.
                        </p>
                        <p className="text-[#575455] text-[16px] leading-relaxed mb-4">
                            Any reference to any statute, ordinance or other law includes all regulations and other instruments and all consolidations, amendments, re-enactments or replacements for the time being in force.
                        </p>
                        <p className="text-[#575455] text-[16px] leading-relaxed">
                            Without prejudice to any other specific requirement which may be laid out in this User Agreement and your use of the Website and the Services and specifically, your acceptance of these terms and conditions contained herein shall be deemed to be a representation from you that you are above 18 years of age, or possess legal parental or guardian consent, and are fully able, conscious and competent to enter into this User Agreement and make your investment decisions, execute the investment transactions, evaluate the advice, if any, and confirm to abide by and comply with the terms set forth herein. The User agrees that any transactions carried out through the Website shall be subject to the provisions contained in the respective Scheme Information Documents and/or Statement of Additional Information and/or Key Information Memorandum, as and when updated by relevant addenda.
                        </p>


                    </div>

                    {/* Usage/Registration / Enrolment and Termination */}
                    <div className="mb-8">
                        <h3 className="text-[18px] font-semibold text-[#E6AF1C] mb-4">Usage/Registration / Enrolment and Termination</h3>
                        <p className="text-[#575455] text-[16px] leading-relaxed mb-4">
                            The Users shall only be allowed to avail the Services on the Website after the User completes the KYC, Investment Readiness and Information Verification process and provides the complete personal information in accordance with the Know Your Client ("KYC") guidelines issued by the Securities and Exchange Board of India ("SEBI") and/or any other regulatory / government agencies or authorities from time to time.
                        </p>
                        <p className="text-[#575455] text-[16px] leading-relaxed mb-4">
                            By registering with Finyzer Assets or by enrolling as its customer, either as a sub-distributor or as an end investor, directly or indirectly through its sub-distributors, you certify that the information you may provide, now or in the future, is accurate. Finyzer Assets reserves the right, in its sole discretion, to deny you access to the Website or any portion thereof without notice for the following reasons:
                        </p>

                        <div className="grid grid-cols-1 gap-[15px] mb-4">
                            <div className="flex items-start gap-2 md:gap-4">
                                <FontAwesomeIcon icon={faHandPointRight} className="text-[#E6AF1C] text-[16px] mt-1" />
                                <p className="text-[#575455] text-[16px]">
                                    Immediately by Finyzer Assets for any unauthorized access or use by you.
                                </p>
                            </div>

                            <div className="flex items-start gap-2 md:gap-4">
                                <FontAwesomeIcon icon={faHandPointRight} className="text-[#E6AF1C] text-[16px] mt-1" />
                                <p className="text-[#575455] text-[16px]">
                                    Immediately by Finyzer Assets if you assign or transfer (or attempt the same) any rights granted to you under this User Agreement or any Client Agreement or
                                    any Sub-broker Agreement that you may have entered with Finyzer Assets;
                                </p>
                            </div>
                            <div className="flex items-start gap-2 md:gap-4">
                                <FontAwesomeIcon icon={faHandPointRight} className="text-[#E6AF1C] text-[16px] mt-1" />
                                <p className="text-[#575455] text-[16px]">
                                    Immediately, if you violate any of the other terms and conditions of this Agreement The termination or cancellation of this Agreement shall not affect any right
                                    or relief to which Finyzer Assets may be entitled to, at law or in equity. Upon termination of this Agreement, all rights granted to you will terminate and revert to
                                    Finyzer Assets. Except as set forth herein, regardless of the reason for cancellation or termination of this User Agreement, the fee charged if any for access to
                                    Finyzer Assets is non-refundable for any reason.
                                </p>
                            </div>
                        </div>
                    </div>

                    {/* License */}
                    <div className="mb-8">
                        <h3 className="text-[18px] font-semibold text-[#E6AF1C] mb-4">License</h3>
                        <p className="text-[#575455] text-[16px] leading-relaxed">
                           Finyzer Assets hereby grants you a limited, non-exclusive, non-assignable and non-transferable licence to access the Website provided and expressly conditioned upon your agreement that all such access and use shall be governed by all the terms and conditions set forth in this Agreement.
                        </p>
                    </div>

                    {/* NOT an Investment Advice */}
                    <div className="mb-8">
                        <h3 className="text-[18px] font-semibold text-[#E6AF1C] mb-4">NOT an Investment Advice</h3>
                        <p className="text-[#575455] text-[16px] leading-relaxed">
                           The information on the Website is provided for information only and does not constitute, and should not be construed as, investment advice or a recommendation to buy, sell, or otherwise transact in any investment including any products or services or an invitation, offer or solicitation to engage in any investment activity. The information on the Website is provided solely on the basis that you will make your own investment decisions and Finyzer Assets does not take account of any investor’s investment objectives, particular needs, or financial situation. In addition, nothing on this Site shall, or is intended to, constitute financial, legal, accounting or tax advice. It is strongly recommended that you seek professional investment advice before making any investment decision. Any investment decision that you make should be based on an assessment of your risks in consultation with your investment adviser.
                        </p>
                    </div>

                    {/* Investment Risks */}
                    <div className="mb-8">
                        <h3 className="text-[18px] font-semibold text-[#E6AF1C] mb-4">Investment Risks</h3>
                        <p className="text-[#575455] text-[16px] leading-relaxed">
                          There are significant risks associated with an investment in any products or services provided by Finyzer Assets. Investment in the products and services is intended only for those investors who can accept the risks associated with such an investment (including the risk of a complete loss of investment) and you should ensure you have fully understood such risks before taking any decision to invest. These Terms do not represent a complete statement of risk factors associated with an investment in any of the products. The offering documentation contains risk warnings which are specific to the relevant products. You should consider these risk warnings carefully and take appropriate investment advice before taking any decision to invest.
                        </p>
                    </div>
                </div>
            </section>
        </div>
    );
};

export default TermsOfUse;
